version: '3'

services:
  web:
    image: monitoring-test:latest
    ports:
      - 80

    environment:
      VIRTUAL_HOST: monitoring.pecka.test
      GITHUB_APP_ID: 83da4ba9e96545b4aa7b
      GITHUB_SECRET_KEY: 8878a7725f726d260a992288c28705f4760753b4
      GITHUB_ADMIN_ID: 123

      SLACK_HOOK_URL: ''

      DATABASE_HOST: 'monitoring'
      DATABASE_USER: 'monitoring'
      DATABASE_PASSWORD: 'monitoring'
      DATABASE_NAME: 'monitoring'

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  database:
    image: mariadb:latest
    volumes:
      - database:/var/lib/mysql
      - ./migrations/structures:/docker-entrypoint-initdb.d:cached,ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: monitoring
      MYSQL_PASSWORD: monitoring
      MYSQL_DATABASE: monitoring

  adminer:
    image: adminer:latest
    ports:
      - 8080
    environment:
      VIRTUAL_HOST: adminer.monitoring.pecka.test
    links:
      - database:db
    depends_on:
      - database

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      VIRTUAL_HOST: rabbitmq.monitoring.pecka.test
      VIRTUAL_PORT: 15672

volumes:
  database:

networks:
  default:
    external:
      name: nginx-proxy
