apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080 #expose port z dockeru
---

apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: monitoring
spec:
  selector:
    app: adminer
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081