apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: jakubenglicky/pecka-monitoring-test:dev
          ports:
            - containerPort: 80 #expose port z dockeru
          envFrom:
            - secretRef:
                name: monitoring-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: monitoring
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080