apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mariadb:latest
          ports:
            - containerPort: 3306 #expose port z dockeru
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'

---

apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: monitoring
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306